CREATE TABLE [User] (
	[Id] INTEGER PRIMARY KEY IDENTITY(1,1),
	[Password] VARCHAR(MAX) NOT NULL,
	[Username] VARCHAR(100) UNIQUE NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	[Firstname] VARCHAR(100) NOT NULL,
);
